### ISSUE TITLE
on submitNonce there is no deadline

### ISSUE THREAD

**Issue by matbogdan79** [de-luxe/burstcoin-jminer#40]
Please check the submitNonce procedure for the pool.
There is no deadline or x-deadline that should get the current miner nonce calculated deadline.
The x-deadline is used by CreepSky to pass the actual deadline in sec or dedline is used by Blago to pass the deadline based on baseTarget.

on NetworkSubmitPoolNonceTask.java is only one change:

      ContentResponse response = httpClient.POST(poolServer + "/burst")
        .param("requestType", "submitNonce")
        .param("accountId", numericAccountId)
        .param("nonce", nonce.toString())
>>>>        .param("x-deadline", calculatedDeadline.toString())
        .header("X-Miner", HEADER_MINER_NAME)
        .header("X-Capacity", String.valueOf(gb))
        .timeout(connectionTimeout, TimeUnit.MILLISECONDS)
        .send();

Please add it to your miner.

**Comment by de-luxe** [comment]
@matbogdan79 Doesn't the pool have to calculate/validate the deadline anyway by nonce? Sure i can add that, but i don't get why it is needed. Please point me to the pool software repository using that.

**Comment by matbogdan79** [comment]
This is used by uray pool source.
![image](https://user-images.githubusercontent.com/10978746/28741189-acb96432-7419-11e7-92e6-1b9b04c31b4d.png)
I am trying to prevent with a pool checker this kind of submit by jminer - this is the only miner that have this missing.
This is required to prevent bad nonces to be processed by the java wallet and therefore reduce the CPU time on that.
Blago miner has it , CreepMiner has it.
Please add it to jminer - this being used by the most big miners and we need a way to filter the bad nonce's.
The uray pool calculate/validate it trough the java wallet and that is a pain when miners submit nonce's like that.

Thank you for understanding and cooperation.

**Comment by de-luxe** [comment]
@matbogdan79 Thanks for the hint, i will add it.

**Comment by Creepsky** [comment]
Just to make this clear because I already had this problem when I implemented this :)
Blago miner and creepminer uses this field mainly intern for forwarding.

Blago uses `/burst?requestType=submitNonce&...&deadline=123`, where deadline is the raw deadline (dont know how to call this, its basically `real deadline * basetarget`.

creepminer uses `X-Deadline` in the POST body of the submit, what represents the deadline in seconds as a string.

Maybe we should standardize the fields so the miners will become all compatible :) and also for @matbogdan79 it will be easier to check.

**Comment by de-luxe** [comment]
@Creepsky Ok with me, i'm also open to in general discuss miner<->pool api enhancements ... i would have added X-Deadline to the header like X-Miner and X-Capacity ...
