### ISSUE TITLE
Getting inconsistent duplicate/overlapping plot file error 

### ISSUE THREAD

**Issue by FilipMlekicki** [de-luxe/burstcoin-jminer#55]
Couple issues that may be related. I am running the miner on mac w/ java 9.0.4 connected to a Synology NAS via ethernet and router, with a few externals attached to the NAS itself. Plot files are sequential and not overlapping and the miner will run fine for several rounds and then throw up an error that the plot files are overlapping, ie. "Error: ReaderPartLoadedEvent for unknown chunkPartStartNonce: "

Additionally the only way that i can actually get the miner to run with anything more than 1 plot drive/directory, is by setting the reader threads to 1. If I change this the miner does nothing past the first round. I have also tried just reading all the externals directly and through a hub with the same behavior. 

Lastly, sometimes i also get the  message that the read was "stopped" many times in a row.

**Comment by de-luxe** [comment]
@FilipWalkWell Thanks for feedback, turns out you are not the only mac user with issues. 
https://github.com/de-luxe/burstcoin-jminer/issues/49#issuecomment-368284991
Currently i sadly have no clue what could cause the issues, that readerTheads=1 leads to miner working indicates a thread concurrent issue ... sadly i can not reproduce it yet. Hopefully next release will fix thoose issues.

On showDriveInfo=true the stop messages will appear if new round starts before current was finished.

**Comment by de-luxe** [comment]
@FilipWalkWell Try using java8 instead of java9 ... seams using java9 causes issues with jminer.

**Comment by FilipMlekicki** [comment]
Java 8 seems to have it running without overlap issue, but will still only run with ReaderThreads=1. Also still getting lots of stopped messages. 

Thanks, and looking forward to the next release!

**Comment by MrDrProfK** [comment]
@de-luxe @FilipMlekicki I'm having the same problem on MacOS 10.9.5 with Java 1.8.0_171
Unfortunately, setting ReaderThreads=1 doesn't seem to resolve the overlap issue for me. Previously I had an overlap in plot files (though the overlapping plot wasn't being mined and was on a different drive), but have since deleted the overlapping plot. Is there a cache I need to clear? Is there a previous version of JMiner that I can use to avoid these issues?

Thanks.

(I should also mention that I use MJMiner to plot)

**Comment by de-luxe** [comment]
@MrDrProfK No there is no cache to clear, jminer will scan your drives at least on every start. Check jminer.properties for maybe duplicate listed drives ... if thats not the case, you most likely have some overlaping ... as long you do not post more info like plotfile names or jminer.properties etc. i can not help further.

**Comment by de-luxe** [comment]
@MrDrProfK @FilipMlekicki please re-open / report if version 0.5.2-RELEASE does not fix your issues.
